version: '3.9'
services:
  gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    ports: 
      - 5757:80
    depends_on:
      - api1   
      - api2
      - identity-server
  identity-server:
    build:
      context: ./IdentityServer
      dockerfile: ./Dockerfile 
    env_file: 
      - ./production.env
    ports: 
        - 5758:80        
  api1:
    build:
      context: ./Api1
      dockerfile: ./Dockerfile          
  api2:
    build:
      context: ./Api2
      dockerfile: ./Dockerfile   
  account-service:
    build:
      context: ./AccountService
      dockerfile: ./Dockerfile   
    depends_on:
      - identity-server      