version: '3.9'
services:
  gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    ports: 
      - 5757:80
    depends_on:
      - api1   
      - api2
      - identity-server
  identity-server:
    build:
      context: ./IdentityServer
      dockerfile: ./Dockerfile 
  api1:
    build:
      context: ./Api1
      dockerfile: ./Dockerfile          
  api2:
    build:
      context: ./Api2
      dockerfile: ./Dockerfile   
 