version: '3.9'
services:
  gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    ports: 
      - 5566:80  
  api1:
    build:
      context: ./Api1
      dockerfile: ./Dockerfile   
    depends_on:
      - gateway          
  api2:
    build:
      context: ./Api2
      dockerfile: ./Dockerfile   
    depends_on:
      - gateway 